### ISSUE TITLE
About the _cur_task in inference

### ISSUE THREAD

**Issue by Gary-code** [sun-hailong/CVPR24-Ease#3]
Congratulations on your paper accepted by CVPR 2024.
I am curious about that in [#line](https://github.com/sun-hailong/CVPR24-Ease/blob/fc204a237da873dcc7d46ed0956211bd9b0e23d8/utils/inc_net.py#L177) and Eq. 12 in the paper, is the task id known during inference?

**Comment by sun-hailong** [comment]
Hi @Gary-code,
We don't use the task id for inference; instead, we solely use it to calculate the reweight subspace during training. I think this is simply a different implementation approach, as it can be calculated after training the current task and the calculated weight is used only for inference. On the other hand, we only know the current task, which is the maximum task id, and we are unable to obtain the task id for each test example.
