### ISSUE TITLE
Reproducing other baselines

### ISSUE THREAD

**Issue by kandeldeepak46** [sun-hailong/CVPR24-Ease#5]
Hi Authors,

Thank you for sharing. Great work!
The paper is well articulated!

Can you please also share the other baseline (LwF,  SDC, L2P ...) codes that you compared within the paper? 

Thank you!

**Comment by zhoudw-zdw** [comment]
Thank you for your interest in our work. For most of the compared methods, you can refer to this [toolbox](https://github.com/sun-hailong/LAMDA-PILOT), which contains extensive pre-trained model-based methods.

For some typical continual learning algorithms, you are suggested to refer to this [toolbox](https://github.com/G-U-N/PyCIL) (they share similar code structures)for easy modification.
