### ISSUE TITLE
> The reweight process does not rely on the task ID. It only changes the logit calculation process depending on whether the item belongs to the diagonal component. To understand this point, I suggest you review Eq. 10 to Eq. 12 in the main paper.

### ISSUE THREAD

**Issue by lemoshu** [sun-hailong/CVPR24-Ease#8]
> The reweight process does not rely on the task ID. It only changes the logit calculation process depending on whether the item belongs to the diagonal component. To understand this point, I suggest you review Eq. 10 to Eq. 12 in the main paper.
> 
> Take a 2-task CIL for an example. The basic logit calculation for the first task classes is achieved by matching \phi_1(x) to P11 and matching phi_2(x) to P12 and aggregating them. Since P11 is the diagonal component while P12 is not, the reweighting process only adjusts the combination weight among them.
> 
> It is clear that we do not utilize the task ID since deciding the diagonal component is irrelevant to it.

I have a follow-up question: taking this 2-task CIL for example after the entire training, based on your clarification, given an image X originally from task 1, we still need to know that X belongs to task 1. Then, use the diagonal component P11 more. Is it the task id? Because if you do not give the task 1 (identity), the model cannot distinguish where the image X is from and may use P22 (also the diagonal).

_Originally posted by @lemoshu in https://github.com/sun-hailong/CVPR24-Ease/issues/4#issuecomment-2503962461_

**Comment by zhoudw-zdw** [comment]
The above process calculates the logit for the first task with respect to X. When calculating the logit for the second task, the weight of P22 will be highlighted in the same way.

It’s important to note that the diagonal components are highlighted during inference, regardless of the task ID.

**Comment by lemoshu** [comment]
> The above process calculates the logit for the first task with respect to X. When calculating the logit for the second task, the weight of P22 will be highlighted in the same way.
> 
> It’s important to note that the diagonal components are highlighted during inference, regardless of the task ID.

Thanks for the prompt reply. I am still confused. Like here, **you know you are handling task 1** during inference, so you use diagonal P11 rather than P22. But, after the entire training, giving a **random image X**, how does the unified model identify which task the image X belongs to and then highlight the diagonal component? I mean, in the evaluation, you are calculating the performance for each task but this implicitly gives a task ID to identify which diagonal should be highlighted. But how about a random image X and you don't know which task is it from?

**Comment by lemoshu** [comment]
> The above process calculates the logit for the first task with respect to X. When calculating the logit for the second task, the weight of P22 will be highlighted in the same way.
> 
> It’s important to note that the diagonal components are highlighted during inference, regardless of the task ID.

Note that I highlight my main concern: **random image X**, but here you literally know the image X is from task b during inference.
![image](https://github.com/user-attachments/assets/63da28de-c51b-4a2d-b615-dd06c8377f35)

**Comment by zhoudw-zdw** [comment]
For a random X, the logit of the first task is P11^T phi1(X)+P12^T phi2(X). The logit of the second task is P21^T phi1(X)+P22^T phi2(X).
Before Eq. 12, the output is [P11^T phi1(X)+P12^T phi2(X), P21^T phi1(X)+P22^T phi2(X)]
After Eq. 12, the output is [P11^T phi1(X)+ \alpha P12^T phi2(X),  \alpha P21^T phi1(X)+P22^T phi2(X)]
I cannot see why you relate this equation to task id, as both tasks share the same modification.

**Comment by kandeldeepak46** [comment]
Without phototype reweighting, the accuracy in CIFAR100 with 20 tasks decreases to 79. The cosine similarity and prototype complement do not play any role.
